### ISSUE TITLE
Opening the extension presents a blank window

### ISSUE THREAD

**Issue by TheMysticLynx** [filipesabella/vscode-live-p5#14]
![image](https://user-images.githubusercontent.com/57817285/111225686-58234c00-859d-11eb-8e67-89727152287f.png)

**Comment by leatherbird** [comment]
Same issue.
macOS 11.2.3, VS Code 1.54.3, live-p5 1.4.2
Doesn't seem to be running.

Occasionally i get the error when starting Live p5 :
**Command 'Open live p5 panel' resulted in an error (Running the contributed command: 'extension.live-p5' failed.)**

**Comment by filipesabella** [comment]
Thanks for the report! I'll take a look this week/weekend.

**Comment by filipesabella** [comment]
https://github.com/filipesabella/vscode-live-p5/commit/26ba277f0ab5cd76a50bfa09fcb93655e20596a4

That took a loong time to find out. New version released, please let me know if it's working for you both.

**Comment by leatherbird** [comment]
That did it for me. Works now!

4 days ago was when I first installed it. So, this is my first time seeing live-p5 in action.
This is great! So convenient! Thank you for making this.

**Comment by filipesabella** [comment]
Ah wonderful! Thank you again for the report and also for the feedback.
