### ISSUE TITLE
video = createCapture(VIDEO); is not working

### ISSUE THREAD

**Issue by q0o0p-kor** [filipesabella/vscode-live-p5#17]
async function setup() {
  myCanvas = createCanvas(640, 640);
  video = createCapture(VIDEO, videoReady);
  video.size(640, 480);
  video.hide();
}

this is my setup function.
but video(webcam) is not working.
how do i make working?

**Comment by filipesabella** [comment]
Hey, thanks for the report! I'll take a look on the weekend.

**Comment by filipesabella** [comment]
Well, this is very strange, I went to fix the other issue and saw this opened one from so many months ago.
I remember very clearly spending some hours on this and reaching the conclusion that webviews inside VSCode can't access the camera, I have no idea why I didn't close this issue, my apologies.
