### ISSUE TITLE
Contents are flipped vertically

### ISSUE THREAD

**Issue by b3ll** [filipesabella/vscode-live-p5#2]
For some reason the preview window has its contents flipped vertically (or treats Y rotations differently)

Here's a preview in VS Code: 
<img width="2032" alt="p5" src="https://user-images.githubusercontent.com/1981722/31588531-15f50b4c-b1a8-11e7-803d-dd90e92ab722.png">

Here's a preview in Chrome:
<img width="1661" alt="p52" src="https://user-images.githubusercontent.com/1981722/31588534-24c0c8dc-b1a8-11e7-9811-90d85ba57928.png">

**Comment by b3ll** [comment]
Actually I think this was just a bug with the bundled version of p5.js. After I manually updated them to the latest versions it rendered correctly.

**Comment by filipesabella** [comment]
@b3ll thanks for the report!

To which version did you update it? I can release a new version of the extension with it.

**Comment by b3ll** [comment]
0.5.16 was the one I used!

**Comment by filipesabella** [comment]
Just published 1.0.3 with p5 0.5.16.

I'd like to figure out a good way to enable users to use their own `index.html` file with minimal configuration.

Thanks again for the report, @b3ll.
