### ISSUE TITLE
Wrong values for width and height when creating Canvas with numbers.

### ISSUE THREAD

**Issue by GeorgePaps** [filipesabella/vscode-live-p5#20]
Starting from 16-09-2021 I noticed that when you define the canvas dimensions with numbers 
(e.g. createCanvas(400,500)), when you try to access those numbers with the width and height variables they
 don't get the values they are supposed to (in this case width 400 and height 500).

![image](https://user-images.githubusercontent.com/43519179/133815903-bcac3ae7-ca2e-4777-93c7-60619c532b61.png)

**Comment by filipesabella** [comment]
Well that's odd, thanks for the report, @GeorgePaps. I'll take a look during the week.

**Comment by filipesabella** [comment]
Hey @GeorgePaps, I can't seem to reproduce this, oddly enough.

Questions:
1. Does it print the correct width if you put the console log inside the `draw` function?
2. How did you get the `output` to show this stuff? I've always used the developer console.

**Comment by GeorgePaps** [comment]
Hey Filipe, 

1) I Encounter the same problem both when using console log at setup and at draw. 

![image](https://user-images.githubusercontent.com/43519179/134217409-a8c6774f-d134-4afc-baaa-67bc65c433f6.png)

2) The output is at the p5canvas console. The problem is that even when I am trying to use the value inside the setup block
 the values are wrong (e.g. when creating a circle with center width/2 and height/2), they are actually the ones the console log 
is printing. 

![image](https://user-images.githubusercontent.com/43519179/134217876-89b03ec1-cb65-43fe-9dbc-e58a8301e8c4.png)

Thanks a lot for the quick response,

**Comment by filipesabella** [comment]
I took this screenshot just to show my setup:
![image](https://user-images.githubusercontent.com/33415/134223486-a4832975-7820-4071-be28-69671a772239.png)

But then I noticed, on your screenshot, that the tab name is `p5canvas`, and that you might be using a different extension:
https://marketplace.visualstudio.com/items?itemName=garrit.p5canvas

The command name to open this extension is "Open live p5 panel".

Can you please double check my theory?

**Comment by GeorgePaps** [comment]
Ohh you are right, sorry for the confusion and thanks a lot for the time.

**Comment by filipesabella** [comment]
No worries at all! I really appreciate you taking the time to create an issue, I wish more people did that.

cheers!
