### ISSUE TITLE
feature request: "open the panel on the left" option

### ISSUE THREAD

**Issue by setanarut** [filipesabella/vscode-live-p5#21]
It's very tedious to move the panel to the left every time. It would be nice if there was such an option.
`"open the panel on the left": true`

**Comment by filipesabella** [comment]
I went in pretty confident this would be easy to implement given [this line of code](https://github.com/filipesabella/vscode-live-p5/blob/master/src/extension.ts#L19), but it seems that this is actually impossible to implement currently:
https://github.com/microsoft/vscode/issues/103828

I tried upgrading to the lastest vscode engine, to no avail. The options when creating the webview only accomodate for different columns to the right of the currently active editor.

To be honest, I'd prefer that webview to be completely detachable of the main window, but there's no API for this yet as well.
