### ISSUE TITLE
Visibility of logs

### ISSUE THREAD

**Issue by pwalsh** [filipesabella/vscode-live-p5#22]
Hi,

I'm testing out this extension. Everything is great except when I console.log I never see the output anywhere.

I have read the notes about this in the project readme, and am aware of the issues noted there. 

Is there any info I can provide to debug this issue?

I'm a regular VS Code user and also comfortable with Javascript so I can also contribute a patch or something if you can point me in the right direction.

Thanks.

**Comment by filipesabella** [comment]
hi @pwalsh, thanks for opening the issue.

just to make sure, did you try opening the dev console on vscode? if you don't know what that is yet, you can open it in the _Help > Toggle Developer Tools_ menu.

**Comment by pwalsh** [comment]
Hi,

Ok, got it. I was sure that when you wrote dev console you refer to the panes when opening a terminal.

Thanks.

**Comment by filipesabella** [comment]
Ah fantastic, thank you. I'll update the README for clarity.
