### ISSUE TITLE
new WebView API

### ISSUE THREAD

**Issue by wejust1027** [filipesabella/vscode-live-p5#4]
@filipesabella . I really like to use live-p5 you developed, but now vscode-p5canvas has adopted the new WebView API, live-p5 can not run, Is there any updating plan in the near future? thank you!

**Comment by filipesabella** [comment]
Woopsy! Will work on it this week.

Thanks for the report :)

**Comment by wejust1027** [comment]
I'm looking forward to the new version.Thank you again!

**Comment by filipesabella** [comment]
Done!
