### ISSUE TITLE
Manual reload

### ISSUE THREAD

**Issue by ZigiZen** [filipesabella/vscode-live-p5#5]
Would love an option to manual reload with keyboard shortcut when i don't want to change anything just try different "seed" for random stuff. Currently need to switch tabs.

**Comment by filipesabella** [comment]
hey @ZigiZen! thanks for the feedback, and sorry for the delay. I'll take a look at it.

**Comment by filipesabella** [comment]
@ZigiZen found the issue. The webview doesn't reload itself if the new html is the same as the current one.

I've added a little hack to change the html every time one saves the document.

After you update to 1.3.0, you will be able to `(cmd|ctrl)+s` to force reloading the view.
