### ISSUE TITLE
Canvas update on file modified

### ISSUE THREAD

**Issue by pammacdotnet** [filipesabella/vscode-live-p5#7]
Dear Filipe… could you update you extension to update the Live p5 area when the file is modified externally (not necessarily from an explicit Contol+S action)?
This would allow the use of TypeScript in P5. It currently works like charm, but I need to manually switch to the .js tab and press "save" to have the Live area show the results. 
I'd be wonderful to have it reload automatically on any file modification event.

Thank you very much. Greetings from Spain.

**Comment by filipesabella** [comment]
Hello there!

Interesting requirement. I've been thinking about typescript support for some time now, perhaps I could try and just add it.

**Comment by pammacdotnet** [comment]
Thanks Filipe… but, just to be 100% clear, I'm not asking for TS support, just "file modfied" event-handling (or at least an user configurable option to enable it). It should not take long. Thanks in advance.

**Comment by filipesabella** [comment]
@pammacdotnet sure thing!

just a question, since I'm playing with the TS compiler here, the whole updating-without-refreshing with typescript doesn't work with your setup, right?

**Comment by filipesabella** [comment]
@pammacdotnet also, another question. What do you think it'd be a good solution as to which file to watch?

I implemented something quick here to simply watch the file that was open when the extension was activated. What do you think?

**Comment by pammacdotnet** [comment]
>  the whole updating-without-refreshing with typescript doesn't work with your setup, right?
No, it does not work (as it should not do it, of course). 

> I implemented something quick here to simply watch the file that was open when the extension was activated. What do you think?

Wonderful! Enough (for me)! TS is, definitely, the #1 JS "compiler" these days, but there are also other JS "transpilers" (CoffeeScript, etc.)… so a solution of this type (watch the already open/drawn js file) is more transversal. I personally don't mind opening the file, loading the extension and closing the tab with the js file (further changes would then take place in the .ts code and are transpiled to js with the ts compiler in watch mode). 

However, a more TS-like solution would be to try to read the outFile option in the tsconfig.json file in the project's directory. This file is supposed to conglomerate all the *.ts code into a single js file. This file could be the one to be watched. But again: this is a TS-only solution. Up to you, Filipe!

I'm very grateful for your (super fast) help!

**Comment by filipesabella** [comment]
@pammacdotnet I've released the 1.4 version with the change you requested + rudimentary typescript support (mostly for myself haha was postponing it for a while).

When you can, please let me know if it works for you.

**Comment by pammacdotnet** [comment]
@filipesabella I now get "command 'extension.live-p5' not found". The extension seems to install/update fine. Also tested in Code and Code Insiders. 
BTW, could you also enable or give hints about using the instance mode of P5?

**Comment by filipesabella** [comment]
@pammacdotnet ah I found the error. when running the extension in debug mode the dependencies resolve in a different way than in production. I'm sorting the issue out.

**Comment by filipesabella** [comment]
@pammacdotnet sorted! please let me know if the actual features work when you can haha :) 1.4.2 is the good version.
