### ISSUE TITLE
TypeScrip + live p5 + instance mode 

### ISSUE THREAD

**Issue by pammacdotnet** [filipesabella/vscode-live-p5#8]
In order to be able to use P5 in instance mode, you still need to add a `global.d.ts` file in the root directory with this content:

```typescript
import module = require('p5');
import * as p5Global from 'p5/global' 
export = module;
export as namespace p5;
declare global {
    interface Window {
        p5: typeof module,
    }
}
```

and install p5 with npm (`npm i p5 --save)`. 

I also have to quickly open (or switch to the `global.d.ts` file mentioned above) in order to have VS code detect de p5 namespace (then, the TS linter stops complaining about `Cannot find name 'p5'`)… but after that simple gesture, everything works fine.

**Comment by pammacdotnet** [comment]
A quick disclaimer… my previous comment is not an _issue_, just something you can add to your `readme.md` file 😉.

**Comment by filipesabella** [comment]
Ah nice, thank you!
