### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by ProfAndreaPollini** [filipesabella/vscode-live-p5#9]
Hi, 
 i'm working on a project for my classroom. I started from a p5 preview plugin and use come of your code in order to make it work better (console.log in the debug window was the problem that make me find this plugin not useful because I want to use it with my students at school). I look at you repo in order to check the license and find that you haven't one, so now I have to delete my project and I can'r deliver it to my students. It'n not a production code but perhaps the community will take some advantages if I can publish it. 

I think you will choose a license soon, so I can deliver my project, otherwise I will remove every code form your repo and redo that part in some other way.

good evening from Italy

**Comment by filipesabella** [comment]
Glad to hear this is useful to you, Andrea!
Shame that using the developer tools doesn't suit your use case.

I've added the license file, thanks for the feedback!
